### ISSUE TITLE
What is the correct way to upgrade? 

### ISSUE THREAD

**Issue by costis94** [costis94/bookcut#21]
What is the correct way to upgrade (using the install link in the main page seems to point/download an old version).
I am stuck on 1.3.3

_Originally posted by @DarrenPIngram in https://github.com/costis94/bookcut/issues/14#issuecomment-863771682_

**Comment by costis94** [comment]
@DarrenPIngram

Hello.

What's is your version of pip? Please run:
`pip --version`.

You can upgrade pip using:
`python -m pip install --upgrade pip`

For updating bookcut you can:
`pip install bookcut --upgrade`

For more information you can read:
[Pip Tutorial](https://www.datacamp.com/community/tutorials/pip-python-package-manager)

**Comment by DarrenPIngram** [comment]
I had pip v2 and v3 installed.

Looking at upgrading per your instructions with pip3 brings up further errors. I don't know If it is my end or this end...

It seems v 1.3.7. is available however.

di@MacPro ~ % pip3 install bookcut --upgrade
Requirement already satisfied: bookcut in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.3.6)
Requirement already satisfied: mechanize in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (0.4.5)
Requirement already satisfied: click>=7.1.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (8.0.1)
Requirement already satisfied: pyfiglet in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (0.8.post1)
Requirement already satisfied: requests in ./Library/Python/3.9/lib/python/site-packages (from bookcut) (2.25.1)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (4.61.1)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (4.9.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bookcut) (1.2.4)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from beautifulsoup4->bookcut) (2.2.1)
Requirement already satisfied: html5lib>=0.999999999 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from mechanize->bookcut) (1.1)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from html5lib>=0.999999999->mechanize->bookcut) (1.16.0)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from html5lib>=0.999999999->mechanize->bookcut) (0.5.1)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas->bookcut) (1.20.2)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas->bookcut) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas->bookcut) (2.8.1)
Requirement already satisfied: idna<3,>=2.5 in ./Library/Python/3.9/lib/python/site-packages (from requests->bookcut) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./Library/Python/3.9/lib/python/site-packages (from requests->bookcut) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests->bookcut) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in ./Library/Python/3.9/lib/python/site-packages (from requests->bookcut) (4.0.0)
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
