### ISSUE TITLE
No mirrors available or no Internet Connection!

### ISSUE THREAD

**Issue by Taektiek** [costis94/bookcut#3]
When I tried the example command it gave these errors.

```
Searching for White Fang by Jack London
No mirrors available or no Internet Connection!
No mirrors available or no Internet Connection!
No mirrors available or no Internet Connection!

No mirrors found or bad Internet connection.
Please,try again.

```

**Comment by costis94** [comment]
This is not a BookCut bug, it's normal program behavior. 

This is probably happening because your country or ISP provider has banned Libgen mirrors. 
The only solution is to append the list of mirrors. 

Do you have a working Libgen mirror in your country so I can add it?

**Comment by Taektiek** [comment]
http://gen.lib.rus.ec/
This one works, I think.

**Comment by costis94** [comment]
OK I will added to the mirror list in the next commit.
Until then you can check it by adding the url in the mirror_checker.py inside bookcut folder.

**Comment by Taektiek** [comment]
Okay, thanks for the help!
