### ISSUE TITLE
Why clean_screen and is there anyway to avoid it ?

### ISSUE THREAD

**Issue by thierrydev** [costis94/bookcut#5]
Hello

Why do you clear the console with [def clean_screen():](https://github.com/costis94/bookcut/blob/cbbde24c2e5f6910c6b78c0017b6dd8b86585946/bookcut/bookcut.py#L85)

Is it really necessary ?

**Comment by costis94** [comment]
I added clean_screen() for a better-looking working environment.  Do you think that is annoying? 
I'm currently working for a setting's file addition so maybe I have to add it like an option. What do you think?

**Comment by thierrydev** [comment]
I think it's a great idea
Maybe in this settings file a user can also add libgen mirrors

**Comment by costis94** [comment]
Oh that's a good suggestion, maybe 2 separate files is better idea!

With a configuration option inside the BookCut so the user do not have to mess with files!

Just to run `bookcut config` and change the settings!

**Comment by costis94** [comment]
> I think it's a great idea
> Maybe in this settings file a user can also add libgen mirrors

Hello there. 
I just uploaded version 1.3.0 with config option. 
Please check   `bookcut config - - help` for more. Thanks for your idea.
