### ISSUE TITLE
forced option for bookcut list abruptly ends with no downloads

### ISSUE THREAD

**Issue by FranPhobia** [costis94/bookcut#6]
When using     
`$ bookcut list --forced -f path/to/txt -d path/to/destination `     
the program will just end with no error or further information or output
![bookcut](https://user-images.githubusercontent.com/55863700/89644697-0fc0e480-d87e-11ea-8b32-44c01258d40b.gif)

**Comment by costis94** [comment]
Thanks for the report.
Issue solved. Just an indent error I made!
Please update to version 1.2.3 with pip.
