### ISSUE TITLE
Feature Request: Dot File Configuration / Download Folder Issue

### ISSUE THREAD

**Issue by typkrft** [costis94/bookcut#7]
It would be great if we could have a dotfile config for options. Something stored in $HOME/.config so we can keep configured cross platform. Not that there is a lot to configure at the moment. Sans a configuration it might be nice to ask where files should be saved on first run. Lastly setting the Download Folder doesn't seem to work. 

macOS Catalina 10.15.6 (19G73)
Bookcut install 8/10/20 from Source

```shell
$ bookcut config --download_folder ~/Downloads

>>> Destination path changed!
 >>> /Users/<userName>/Downloads
```
However, after setting this when I download some book, it does not seem to work.

**Comment by costis94** [comment]
Thanks for your time and your report.

BookCut is a newborn project so needs some time. I will publish a new version for the bug as soon as possible.

**Comment by typkrft** [comment]
No worries. Keep up the great work!
