### ISSUE TITLE
add md5 parsing to list download option

### ISSUE THREAD

**Issue by windowswithoutborders** [costis94/bookcut#8]
Can you add support for parsing a list for md5 values that a book is associated with? It would be much cleaner for downloading a specific version of a book. Thanks!

**Comment by costis94** [comment]
Your suggestion is sounding reasonable and is adding a very useful option for BookCut. As a result I'm going to add it to the next version.

I'm going to add option for downloading a book with a given md5 value, and downloading a list with a givel list of md5 values.

**Comment by windowswithoutborders** [comment]
finally getting around to trying this out. I've tried a lot of the libgen downloaders on github and now with the inclusion of md5 feature I have to say yours is the best I've used :)!
